name: Auto Push and Create PR

on:
  push:
    branches:
      - main   # mainブランチへのpush時に実行されます
  # 必要に応じて、他のイベントに変更できます。

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: cli/cli-action@v2

    - name: Set up GitHub authentication
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" > gh-token.txt
        gh auth login --with-token < gh-token.txt

    - name: Create and push new branch
      run: |
        # スクリプトの内容をここに記載
        git checkout -b ${{ github.event.head_commit.timestamp }}
        git add .
        git commit -m "Auto commit on push"
        git push origin HEAD

    - name: Create Pull Request
      run: |
        gh pr create --base main --head ${{ github.event.head_commit.timestamp }} --title "Auto commit for push" --body "This PR was created automatically"
        gh pr merge --auto --merge
